import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, ArrowLeft, CheckCircle2, Download, FileText, Printer, Search, Trash2, X } from 'lucide-react';
import { deletePrintedFile, listPrintedFiles, PRINTED_FILES_CHANGED_EVENT, retryPrintedFile, type PrintedFileRecord, type PrintedFileStatus } from '../../services/printedFileService';

export const MyPrintedFilesPage: React.FC<{ onBack: () => void }> = ({ onBack }) => {
  const [files, setFiles] = useState<PrintedFileRecord[]>(() => listPrintedFiles());
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState<'all' | PrintedFileStatus>('all');
  const [preview, setPreview] = useState<PrintedFileRecord | null>(null);
  const refresh = () => setFiles(listPrintedFiles());
  useEffect(() => { window.addEventListener(PRINTED_FILES_CHANGED_EVENT, refresh); return () => window.removeEventListener(PRINTED_FILES_CHANGED_EVENT, refresh); }, []);
  const visible = useMemo(() => files.filter((file) => (filter === 'all' || file.status === filter) && `${file.title}${file.subject}`.toLowerCase().includes(query.toLowerCase())), [files, filter, query]);

  return <div className="flex h-full min-h-0 flex-col bg-slate-50">
    <header className="flex h-16 shrink-0 items-center border-b border-slate-200 bg-white px-6"><button onClick={onBack} className="flex h-9 w-9 items-center justify-center rounded-full hover:bg-slate-100"><ArrowLeft size={20} /></button><div className="ml-3"><h1 className="text-[18px] font-semibold text-slate-900">我的文件</h1><p className="text-[10px] text-slate-400">仅保存当前账号的历史打印试卷</p></div><div className="ml-auto flex h-9 w-[260px] items-center rounded-xl bg-slate-100 px-3"><Search size={14} className="text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索试卷或学科" className="ml-2 min-w-0 flex-1 bg-transparent text-[12px] outline-none" /></div></header>
    <div className="flex h-12 shrink-0 items-center gap-2 border-b border-slate-100 bg-white px-6">{([['all','全部'],['failed','待重试'],['success','已打印'],['unknown','待确认']] as const).map(([value,label]) => <button key={value} onClick={() => setFilter(value)} className={`rounded-lg px-3 py-1.5 text-[11px] font-medium ${filter === value ? 'bg-violet-100 text-violet-700' : 'text-slate-500 hover:bg-slate-100'}`}>{label}</button>)}<span className="ml-auto text-[11px] text-slate-400">共 {visible.length} 份</span></div>
    <main className="min-h-0 flex-1 overflow-y-auto p-6">{visible.length === 0 ? <div className="mx-auto mt-20 max-w-sm text-center"><span className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-violet-50 text-violet-500"><FileText size={30} /></span><h2 className="mt-4 text-[16px] font-semibold">{files.length ? '没有匹配的文件' : '还没有历史打印文件'}</h2><p className="mt-2 text-[12px] text-slate-400">完成精准练习组卷并发起打印后，试卷会自动保存在这里。</p></div> : <div className="mx-auto grid max-w-[1100px] grid-cols-2 gap-3">{visible.map((file) => <article key={file.id} className="rounded-2xl border border-slate-100 bg-white p-4 shadow-sm"><div className="flex items-start"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-violet-50 text-violet-600"><FileText size={22} /></span><div className="ml-3 min-w-0 flex-1"><h3 className="truncate text-[13px] font-semibold text-slate-800">{file.title}</h3><p className="mt-1 text-[10px] text-slate-400">{file.subject} · {file.questionCount} 题 · {file.pageCount} 页 · {new Date(file.updatedAt).toLocaleString('zh-CN')}</p></div><StatusBadge file={file} /></div>{file.failureReason ? <p className="mt-3 rounded-lg bg-rose-50 px-3 py-2 text-[10px] text-rose-600">失败原因：{file.failureReason}</p> : null}<div className="mt-4 flex items-center gap-2"><button onClick={() => setPreview(file)} className="h-8 rounded-lg bg-slate-100 px-3 text-[11px] font-medium text-slate-600">预览</button>{file.status === 'failed' ? <button onClick={() => { retryPrintedFile(file.id); refresh(); }} className="flex h-8 items-center gap-1.5 rounded-lg bg-blue-600 px-3 text-[11px] font-semibold text-white"><Printer size={12} />重新打印</button> : <button onClick={() => { retryPrintedFile(file.id); refresh(); }} className="h-8 rounded-lg border border-blue-200 px-3 text-[11px] font-medium text-blue-600">再打一份</button>}<button aria-label="下载 PDF" className="ml-auto flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 hover:bg-slate-100"><Download size={14} /></button><button aria-label="删除文件" onClick={() => { if (window.confirm('删除后将无法从“我的文件”重新打印，是否删除？')) { deletePrintedFile(file.id); refresh(); } }} className="flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 hover:bg-rose-50 hover:text-rose-500"><Trash2 size={14} /></button></div></article>)}</div>}</main>
    {preview ? <div className="absolute inset-0 z-30 flex flex-col bg-slate-200"><header className="flex h-14 items-center bg-white px-5"><button onClick={() => setPreview(null)} className="flex h-8 w-8 items-center justify-center rounded-full hover:bg-slate-100"><X size={18} /></button><h2 className="ml-3 text-[15px] font-semibold">{preview.title}</h2><span className="ml-auto text-[11px] text-slate-400">{preview.pageCount} 页 · 历史打印 {preview.attempts} 次</span></header><div className="flex flex-1 justify-center overflow-auto p-7"><div className="min-h-[900px] w-[650px] bg-white p-14 shadow-xl"><h1 className="text-center text-xl font-bold">{preview.title}</h1><p className="mt-3 border-b border-slate-800 pb-3 text-center text-xs">{preview.subject} · 共 {preview.questionCount} 题</p>{Array.from({ length: Math.min(preview.questionCount, 12) }, (_, index) => <div key={index} className="mt-6 text-[13px]">{index + 1}. 历史试卷题目内容预览<div className="mt-3 h-8 border-b border-dashed border-slate-300" /></div>)}</div></div></div> : null}
  </div>;
};

const StatusBadge = ({ file }: { file: PrintedFileRecord }) => {
  const ok = file.status === 'success';
  return <span className={`ml-3 flex shrink-0 items-center gap-1 rounded-full px-2 py-1 text-[9px] font-semibold ${ok ? 'bg-emerald-50 text-emerald-600' : file.status === 'failed' ? 'bg-rose-50 text-rose-600' : 'bg-amber-50 text-amber-600'}`}>{ok ? <CheckCircle2 size={11} /> : <AlertCircle size={11} />}{file.statusLabel}</span>;
};
